# POP77032 Assignment 1: Text Preparation

## Before Submission

-   Make sure that you can run all cells without errors
-   You can do it by clicking `Kernel`, `Restart & Run All` in the menu
    above
-   Make sure that you save the output by pressing Command+S / CTRL+S
-   Rename the file from `01_assignment.ipynb` to
    `01_lastname_firstname_studentnumber.ipynb`
-   Use Firefox browser for submitting your Jupyter notebook on
    Blackboard.

## Overview

In this assignment you will need to collect and prepare textual data for
analysis. As the data source we will debates in the Dáil Éireann (Irish
Parliament) for the first 2 months of 2025 (but in practice once you
implement a solution for those it should be relatively straightforward
to scale up).

There are 2 broad strategies that can be used to obtain Dáil debates:

1.  Use the [Oireachtas
    website](https://www.oireachtas.ie/en/debates/find/) to scrape the
    debates using R (e.g. `rvest`) or Python (e.g. `Beautiful Soup`).
    There can be different strategies to solve this, but, crucially, the
    website is largely static, so dealing with it as a set of HTML files
    is quite manageable.
2.  Use the [Oireachtas API](https://api.oireachtas.ie/) to scrape the
    debates using R (e.g. `httr2`) or Python (e.g. `requests`). This
    might be a more advanced option, but it is also a lot more powerful
    and flexible. Importantly, this API does not require authentication,
    which makes working with it quite a bit simpler than with many other
    APIs.

## Part 1: Data Acquisition

In this part you will need to write a scraper that collects the data
either directly from the Oireachtas website or using the Oireachtas API.
The data should be collected for the first 2 months of 2025 (January and
February, but the bulk of the debates would be in February).

Depending on how you choose to organise your code, you may choose to
build up a usual tabular dataset straightaway or you might find it
easier to store the data in a different container (e.g. a list of
vectors, a list of lists, a list of dictionaries, etc.) and then convert
it to a tabular format in the next part.

You may use generative AI to help you with trialing different
approaches. If you do use AI, you need to report the version of the LLM
that you are using (e.g. `code-davinci-002`,
`meta-llama-3.1-8b-intruct`, etc.). Hardware permitting, I encourage you
to use offline models to have better control over the data and the
model.

While there maybe also some bindings for the API that are readily
available, none of them are officially supported, so you shouldn’t be
relying on those.

## Part 2: Text Preprocessing

In this part you will need to clean up the collected data. Depending on
how the previous part was implemented it might take more or fewer steps.
The ultimate goal is to have a dataset of the following form:

| dail | vol | no  | date | speaker | text | ntokens | ntypes |
|------|-----|-----|------|---------|------|---------|--------|

where:

`dail` - is the number of the Dáil (e.g. 34th Dáil)

`vol` - is the volume number of the debates (e.g. 1000)

`no` - is the number of the debate in the volume (e.g. 1)

`date` - is the date of the debate (in YYYY-MM-DD form, e.g. 2025-01-01)

`speaker` - is the name of the speaker

`text` - is the text of the speech

`ntokens` - is the number of tokens in the speech

`ntypes` - is the number of types in the speech

Note that you **do not** need to submit the actual dataset. However,
after organising the textual data in this way, you will need to perform
the following steps:

-   Print out the first and last 5 rows of the data
-   Print the dimensionality of the data (number of rows and number of
    columns)
-   Print the total number of unique speakers in the dataset.
-   Print the average number of tokens per speech.
-   Print the average number of types per speech.

## Part One - Data Acquisition 
 In this section, I first scrape the main debate pages and then scrape each individual debate within those pages.

In [4]:
#Libraries
libs <- c("tidyverse",
          "rvest",
          "httr",
          "stringr",
          "quanteda")
install.packages(setdiff(libs, rownames(installed.packages())))

lapply(libs, library, character.only = TRUE)

#using a link from the website directly filtered by date
url <- "https://www.oireachtas.ie/en/debates/find/?debateType=dail&datePeriod=dates&fromDate=01%2F01%2F2025&toDate=27%2F02%2F2025&term=%2Fie%2Foireachtas%2Fhouse%2Fdail%2F34&committee=&member="

#Extracting the links of each main debate page
extract_links <- function(page_url) {
  page <- read_html(page_url)
  hrefs <- page %>%
    html_nodes("a.u-btn-secondary.c-debates-expanding-list__button") %>%
    html_attr("href")
  hrefs_absoloute <- url_absolute(hrefs, page_url)
  return(hrefs_absoloute)
}

debate_links <- url %>% map(extract_links) %>% unlist()
debate_links[1]
pages <- vector("list", length(debate_links))

#after extracting the links, this loop will read each page
for (i in seq_along(debate_links)) {
  message("Reading: ", debate_links[i])
  pages[[i]] <- read_html(debate_links[i])
}

#Because the daily is not on each debate, I will subset it from the main pages
#Following this, I will examine which Dail it is and if it is a constant for my dataframe later

dail <- vector("character", length(pages))

for (i in seq_along(pages)) {
  dail[i] <- pages[[i]] %>%
    html_nodes("p.c-debate-header__meta-item:nth-of-type(2)") %>%  
    html_text(trim = TRUE)
}

dail[1] 

#This function will be used to extract each debate within the main page.
extract_links <- function(page_url) {
  page <- read_html(page_url)
  hrefs <- page %>%
    html_nodes("a") %>%
    html_attr("href") %>%
    .[grepl(
      "/en/debates/debate/dail/\\d{4}-\\d{2}-\\d{2}/\\d+/(#s\\d+)?$", #using regex to represent all the various endings to the url each individual debate has
      .
    )]
  hrefs_absoloute <- url_absolute(hrefs, page_url)
  return(hrefs_absoloute)
}

debate <- debate_links %>% map(extract_links) %>% unlist() #running the function

# Reading each debate within the main debate pages after we've extracted it.
debates <- vector("list", length(debate))
for (i in seq_along(debate)) {
  message("Reading: ", debate[i])
  debates[[i]] <- read_html(debate[i])
}

[[1]]
 [1] "quanteda"  "httr"      "rvest"     "lubridate" "forcats"   "stringr"
 [7] "dplyr"     "purrr"     "readr"     "tidyr"     "tibble"    "ggplot2"
[13] "tidyverse" "repr"      "stats"     "graphics"  "grDevices" "utils"
[19] "datasets"  "methods"   "base"

[[2]]
 [1] "quanteda"  "httr"      "rvest"     "lubridate" "forcats"   "stringr"
 [7] "dplyr"     "purrr"     "readr"     "tidyr"     "tibble"    "ggplot2"
[13] "tidyverse" "repr"      "stats"     "graphics"  "grDevices" "utils"
[19] "datasets"  "methods"   "base"

[[3]]
 [1] "quanteda"  "httr"      "rvest"     "lubridate" "forcats"   "stringr"
 [7] "dplyr"     "purrr"     "readr"     "tidyr"     "tibble"    "ggplot2"
[13] "tidyverse" "repr"      "stats"     "graphics"  "grDevices" "utils"
[19] "datasets"  "methods"   "base"

[[4]]
 [1] "quanteda"  "httr"      "rvest"     "lubridate" "forcats"   "stringr"
 [7] "dplyr"     "purrr"     "readr"     "tidyr"     "tibble"    "ggplot2"
[13] "tidyverse" "repr"      "stats"     "graphics"  "grDevices" "utils"
[19] "datasets"  "methods"   "base"

[[5]]
 [1] "quanteda"  "httr"      "rvest"     "lubridate" "forcats"   "stringr"
 [7] "dplyr"     "purrr"     "readr"     "tidyr"     "tibble"    "ggplot2"
[13] "tidyverse" "repr"      "stats"     "graphics"  "grDevices" "utils"
[19] "datasets"  "methods"   "base"

[1] "https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/"

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-06/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-05/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-01-23/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-01-22/

[1] "34th Dáil"

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/2/#s3

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/2/#s4

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/2/#s5

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/2/#s6

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/2/#s7

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/#s9

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/#s10

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/#s11

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/#s12

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/#s13

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/#s14

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/#s15

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/8/#s16

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/17/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/17/#s18

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/17/#s19

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/17/#s20

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/17/#s21

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/17/#s22

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/#s24

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/#s25

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/#s26

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/#s27

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/#s28

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/#s29

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/#s30

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/23/#s31

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/32/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/33/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/34/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/35/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/36/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/36/#s37

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/36/#s38

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/36/#s39

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-27/36/#s40

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/3/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/3/#s4

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/3/#s5

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/3/#s6

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/3/#s7

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/8/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/9/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/10/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/11/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/12/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/12/#s13

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/12/#s14

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/12/#s15

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s17

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s18

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s19

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s20

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s21

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s22

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s23

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s24

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s25

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s26

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/16/#s27

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/28/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-26/29/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/3/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/4/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/9/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/9/#s10

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/9/#s11

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/9/#s12

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/13/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/14/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/15/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/15/#s16

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/15/#s17

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/15/#s18

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/15/#s19

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/15/#s20

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/21/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/21/#s22

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/21/#s23

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/21/#s24

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/21/#s25

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/21/#s26

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/21/#s27

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/21/#s28

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/29/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/30/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/30/#s31

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/30/#s32

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/30/#s33

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-25/30/#s34

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/2/#s3

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/2/#s4

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/2/#s5

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/2/#s6

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/2/#s7

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/#s9

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/#s10

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/#s11

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/#s12

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/#s13

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/#s14

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/#s15

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/8/#s16

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/17/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/17/#s18

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/17/#s19

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/17/#s20

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/21/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/21/#s22

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/21/#s23

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/21/#s24

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/21/#s25

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/21/#s26

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/21/#s27

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/21/#s28

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/29/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/30/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/31/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/32/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/33/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/34/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/34/#s35

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/34/#s36

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-20/34/#s37

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/3/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/3/#s4

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/3/#s5

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/3/#s6

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/3/#s7

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/8/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/9/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/10/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/11/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/12/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/13/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/14/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/19/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/20/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-19/29/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/3/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/4/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/9/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/10/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/11/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/11/#s12

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/11/#s13

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/11/#s14

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/15/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/16/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/17/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/18/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/18/#s19

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/18/#s20

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/18/#s21

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-18/18/#s22

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/2/#s3

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/2/#s4

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/2/#s5

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/2/#s6

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/2/#s7

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/8/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/8/#s9

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/8/#s10

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/8/#s11

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/8/#s12

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/8/#s13

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/8/#s14

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/8/#s15

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/16/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/16/#s17

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/16/#s18

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/16/#s19

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/16/#s20

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/16/#s21

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s23

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s24

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s25

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s26

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s27

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s28

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s29

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s30

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s31

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/22/#s32

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/33/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/34/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/35/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/36/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/37/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/38/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/39/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/39/#s40

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/39/#s41

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/39/#s42

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-13/39/#s43

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/3/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/3/#s4

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/3/#s5

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/3/#s6

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/3/#s7

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/8/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/9/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/10/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/11/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/11/#s12

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/11/#s13

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/11/#s14

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/15/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/16/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/17/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/22/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/31/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/40/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-12/45/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/1/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/2/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/3/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/8/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/9/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/10/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/11/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/12/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/12/#s13

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/12/#s14

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/12/#s15

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/12/#s16

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s18

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s19

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s20

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s21

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s22

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s23

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s24

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s25

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/17/#s26

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/27/

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/27/#s28

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/27/#s29

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/27/#s30

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-11/27/#s31

Reading: https://www.oireachtas.ie/en/debates/debate/dail/2025-02-06/1/


## Part Two

 In this section, I am continuing to scrape; however I am creating vectors with the variables of interest as I go and will compile them into a dataframe at the very end.

In [17]:
#extracting the date from each individual debate
date <- vector("character", length(debates))
for (i in seq_along(debates)) {
  date[i] <- debates[[i]] %>%
    html_nodes("h1.c-hero__title") %>%
    html_text(trim = TRUE) %>%
    str_remove(".*?,\\s*") %>%
    str_replace("(\\d{1,2}) ([A-Za-z]{3}) (\\d{4})", "\\3-\\2-\\1") %>% #using regex to remove the beginning of the date string and then rearranging the order
    str_replace_all(c("Jan"= "01", "Feb"= "02"))
}

date[1]

vol <- vector("character", length(pages)) #Extracting both Vol and No since they are printed together

for (i in seq_along(debates)) {
  vol[i] <- debates[[i]] %>%
    html_nodes("p.c-hero__subtitle") %>%
    html_text(trim = TRUE)
  
}

# Since they are printed together, I have to use regex to select both of them individually. 
vols <- str_extract(vol, "(?<=Vol\\.\\s)\\d+")
nums <- str_extract(vol, "(?<=No\\.\\s)\\d+")

vols[1]
nums[1]

#I noticed that each speaker is boldened, so to obtain each speaker, I selected the "strong" text in each debate.
speakers <- vector("character", length(debates))
for (i in seq_along(debates)) {
  speakers[i] <- debates[[i]] %>%
    html_nodes("strong") %>%
    html_text(trim = TRUE) %>%
    unique() %>%
    paste(collapse = "; ")
}

speakers[2]

#Extracting all text from each indivdual debate
texts <- vector("character", length(debates))
for (i in seq_along(debates)) {
  texts[i] <- debates[[i]] %>%
    html_nodes("p[id^='para_']") %>%
    html_text(trim = TRUE) %>%
    paste(collapse = " ")
}

texts[2]

ntokens <- integer(length(texts)) 
ntypes <- integer(length(texts))
#extracting tokens and types
for (i in seq_along(texts)) {
  clean_text <- texts[[i]] 
  clean_text <- tolower(clean_text) 
  clean_text <- str_remove_all(clean_text, "[[:punct]]")  #doing some very light cleaning by removing punctuation, given that our objective is unknown.
  clean_text <- str_remove_all(clean_text,"\\d+") 
  
  token <- quanteda::tokens(clean_text) 
  
  ntokens[i] <- quanteda::ntoken(token) #counting all tokens
  ntypes[i] <- quanteda::ntype(token) #counting unique tokens
}

[1] "2025-02-27"

[1] "1063"

[1] "6"

[1] "Deputy Darren O'Rourke; Minister for Education; Deputy Ruth Coppinger; Deputy Richard O'Donoghue"

[1] "1. Deputy Darren O'Rourke asked the Minister for Education if she is aware of the concerns raised by school leaders in relation to the accelerated roll-out of senior cycle reform; if she accepts that the accelerated timeline does not allow enough time for essential preparations; and if she will make a statement on the matter. [8924/25] As this is the first ministerial questions session, I wish the Minister and Minister of State the best of luck in their roles. This is a very important time and I hope we can make progress. Is the Minister aware of the concerns raised by school leaders with regard to the accelerated roll-out of senior cycle reform, if she accepts that the accelerated timeline does not allow enough time for essential preparations and if she will make a statement on the matter? I look forward to working with all colleagues, particularly in this area. I thank the Deputy for asking this question as it is an important and live issue, in particular for students who will sit the leaving certificate in the years ahead. It is for this reason that, in the last few weeks, I have met nearly all the unions and representative bodies representing teachers, principals, schools in general, boards of management, parents and, importantly, students. These conversations were not just about senior cycle reform. What was clear when it came to senior cycle reform is that we are all on the same page and want to ensure we have a senior cycle that is modern, fit for purpose and, above all, prepares our young people for the world we live in today. What is also clear and what we all agree on is that we need to support our teachers and schools in rolling out that programme. I am absolutely committed to continuing the programme of reform of senior cycle to ensure that students benefit from up-to-date curriculums, more diverse skills development and assessments and that we also reduce stress levels. I am also absolutely committed to working with schools, school leaders and teachers in that regard. The world is changing rapidly and it is essential for all of us to properly equip students to succeed in this changing world. The approach to senior cycle redevelopment is about collaboration and engagement with our stakeholders and partners in education to try to deliver this. That engagement commenced back in 2016 and there has been detailed engagement and consultation since then. In 2023, it was announced that the first tranche of two new subjects and seven revised subjects would be introduced in schools in September of this year. Therefore, the first class taking these new and updated subjects will complete their leaving certificate in 2027. The introduction of the new assessment models will help students to develop new skills and reduce the amount of pressure on students. This builds on what is already in place across 28 of the 40 curricular leaving certificate subjects. This is not new when it comes to the additional assessment component but we are trying to modernise and ensure that it applies to the vast majority of subjects. I welcome the fact that the Minister has met stakeholders. It is important that she meets all of the stakeholders in the sector at the earliest opportunity. If she has met them, she must surely have heard their concerns. I have not heard that reflected in her response thus far but they will have detailed them to her. They relate to a range of areas, principally capacity and preparedness, whether in terms of the development of curriculums, the readiness of schools in terms of IT, laboratories and the capacity to take on these changes. The Minister said there is a commitment, as I believe there is, to make this happen in the right way but that takes time and capacity. Is she hearing that from the stakeholders and, if so, how is she responding? I think our stakeholders have outlined a number of things clearly. First, they want to ensure teachers feel appropriately trained and equipped because they want to ensure they are giving their best and students get the best outcomes. A number of training programmes have been developed and delivered already and my intention is to try to intensify that and provide even more supports and resources for teachers. Second, it is about ensuring schools and equipment, particularly for the science subjects, are up to speed. While schools have been given a science implementation support grant, which means that some schools are getting funding ranging from €13,000 to €24,000, with our DEIS schools receiving an additional 10% uplift, I am looking to see if we can provide more to ensure our schools have the equipment they need. We have other programmes, in particular drama, film and theatre studies, where schools have to get cameras, lighting and audio, computer and staging equipment. All of these elements are being provided. Third, there is an issue or concern around artificial intelligence. AI is here and the technology is here to stay but teachers want to know how to use it and incorporate it into how students are working, as well as how they should assess it. There is guidance in place but my Department is working with the National Council for Curriculum and Assessment, NCCA, to ensure we have even more guidance prepared for our teachers. We have spent more time identifying those issues than on spelling out exactly what the timeline will be between now and September for teachers, in the main, and, related to that, for school communities, parents and, most important, students embarking on this new programme from September, if that is the timeline. That detail has to be spelled out to school communities and school leaders at the earliest possible opportunity. If that timeline is not there or there is no schedule to roll it out for this September, the pause button will need to be pressed. I am not convinced from what I have heard so far this morning that such a necessary and detailed plan is there or that a plan for its implementation is in place. If it is not going to be ready, there is a real and continuing risk that this is going to be a very negative experience for all concerned. The most important thing here is that students benefit from the updated curriculums. In order to support teachers, I have asked my Department to intensify engagement. There are meetings happening on a weekly, if not biweekly, basis to ensure we look at how we can provide more and additional training, to ask if more resources need to be provided, to look at how we ensure that clear guidance is in place when it comes to AI and, above all, to ensure that teachers, principals, schools and, in particular, students are supported to avail of what I believe will be a very important transformation for them. There will also be the publication of papers at the beginning of April. Exam papers are usually printed the year before. In this case, it will be done two years before the exams and there will be four papers for each subject, two papers at each level, in Gaeilge and Béarla. This means there will be 72 papers published. It is very important to show the type of exams, projects and assessments that will be coming down the line also. I am absolutely committed to supporting schools, school leaders, teachers and students to ensure they get the best out of this and are as prepared as they can be. This is a very important reform, as we all agree. 2. Deputy Ruth Coppinger asked the Minister for Education if she agrees that the demographics are such in Dublin 15 that there is a need to maintain a school (details supplied) at its existing location and for extra capacity in the Tyrellstown area; and if she will make a statement on the matter. [7671/25] I know the Minister is new to her brief so she may not be familiar with these locations. With regard to Ériu Community College, the Department of Education took an arbitrary decision to move the school from its temporary location to an area 8 km away until such time as it gets its permanent location. The Minister knows that in a suburban area of Dublin, that has a huge impact. I ask her to change that decision. That is a huge demand from the community. I thank the Deputy for raising this question. I appreciate, particularly in areas of huge growth, how important it is to have an adequate number of schools and schools adjacent to and near where students are living. That is the most important thing. My Department has a robust forward planning process which considers population and enrolment data. When it comes to the Dublin 15 area, the Department tells me there is sufficient post-primary school capacity to cater for the existing population. Looking ahead it is also making sure we are looking at projected population expansion, new developments and other people who may come into the area. One relevant indicator is that there are more first-year places available in the existing post-primary schools than there are sixth-class pupils living in the Dublin 15 area. Furthermore, officials in my Department have an ongoing engagement with Fingal County Council in respect of planning new residential developments. Based on this available information and other elements, the school capital projects in the existing schools building programme are expected to cater for the projected additional school place demands resulting from such developments. My Department is satisfied there is no requirement for a new school in that area. However, it has established that there is currently considerable movement of Dublin 15 pupils out of the local communities in which they live to attend post-primary schools. This is most acute in the Mulhuddart-Tyrellstown planning area where enrolment numbers are significantly lower than the school-going population. There are currently more than 1,000 post-primary school pupils leaving this area each day to attend school in other parts of Dublin 15. Ériu Community College, as the Deputy mentioned, was established in 2020 on an interim basis in Dublin 15. This was in response to the identified deficit of local capacity. My Department has determined that Hollywoodrath is the most appropriate permanent location for this school and will provide much-needed capacity in the Mulhuddart-Tyrellstown area, while freeing up capacity in other schools in Dublin 15. That assists in addressing the imbalance of post-primary school capacity across the area. I will refer to the other schools where we know there is additional capacity. The reality is that both areas need secondary schools. I will give the demographics. With all due respect, the Department of Education has had an inglorious history of misplanning educational need in this area and, I am sure, in many others. Ongar, where Ériu Community College is currently located, had the highest birth rate in 2024, according to the CSO. Some 32% of the population is under 18, so where are they to go to school? The only school in the area is at capacity. Fingal, overall, has the youngest population in the country, so there is going to be a massive need for schools in all locations. I know the need in Tyrellstown, which is an area in which my daughter went to school. It needs a school as well. That is the reality. We are asking the Minister to stop the penny-pinching. People should not have to campaign for schools. They should be able to get a school. There are no transport links whatever between both areas. I will outline the capacity that exists in that area. Hansfield Educate Together Secondary School was established for 1,000 pupils. It has 848 pupils enrolled at present. Edmund Rice College, which was established for 1,000 pupils, has 813 pupils enrolled at present. An extension planned for Castleknock Community College will provide approximately 200 additional places. That is essentially a school between the three colleges which have capacity. In addition, there is scope for further expansion in the existing post-primary schools should additional places be required. It seems the demand and need are in the Tyrellstown area, where 1,000 pupils are leaving the area to go to other schools. The intention was that this school would never be permanent. It was to be a temporary base until the new school was developed. I appreciate this might impact the students who are currently in the school, as the Deputy mentioned. They are moving 9 km away. However, by the time the permanent school is built, the majority of those will have moved on. The class of 2027-28 will be new. However, the transition for those who are left will have to be carefully managed. The Department will continue to review this. As the Deputy said, we have to do that because demographics change over time. We are way over time. There are TDs in the area from the Minister's own party demanding the schools. This is not just the Opposition. There is unanimity that both locations need schools. If the Minister is telling parents they have to go to Tyrellstown from the Ongar catchment, which is a different catchment, does she have transport lined up? I have already sent her Department a group of parents who have no transport between these areas. They cannot get school transport and there is no bus link. The reality is that this is penny-pinching by the Minister's Department. There is no other reason. It will be a blow to Dublin 15 to cede that this school will move, because we need schools in both locations and we are sick, sore and tired of having to have public meetings and protests for mainstream schools. I will say nothing of the fact that there is a task force in Dublin 15 on special education. The Minister has already demonstrated that her Department cannot plan educational provision in the area. This is yet another example and we want her to reverse this decision. The reason that Ériu Community College is moving back is that there are 1,000 pupils moving out of the Mulhuddart-Tyrellstown area every day to attend other parts of the school. I appreciate the Deputy's point that other parts of the community are expanding and growing. The Department has to plan ahead looking at the data it has and is available. To plan for school provision, you have to look at the demographic data. It is divided into 314 different school areas from a range of sources. There is the CSO data, the child benefit data, school enrolment data as well as developments in the local authorities. The Deputy has outlined it is a young and growing population. This is taken into consideration when there is a new development and new schools are being looked at and, in particular, what area they should go into. It is on that basis that these decisions have been taken, but I am open to this because I know in the south of Meath in my home county there has been a massive growth in population. Where we need additional schools to those that have already been planned, we need to always keep these figures and projections under review. It will take time for this school to move to its new location, so the students the Deputy has mentioned will most likely serve their school time----- Thank you, Minister, we are way over. -----and finish their schooling in the area they are currently in. Of course, any issues around transport and so on have to be addressed. 3. Deputy Darren O'Rourke asked the Minister for Education what additional demand for special class and special school places for September 2025 is now anticipated at primary and secondary school level; what measures she is taking to ensure the necessary school buildings, staff and resources are in place to meet that demand; if emergency measures are expected; and if she will make a statement on the matter. [8925/25] I ask the Minister about school places in south County Meath. We will need additional places in Dunshaughlin for this September. What additional demand for special class and special school places for September 2025 is now anticipated at primary and secondary school level? What measures is the Minister taking to ensure the necessary school buildings, staff and resources are in place to meet that demand, if emergency measures are expected, and if she will make a statement on the matter? I thank the Deputy for the question, and I look forward to working with everybody in this role for the betterment of all because there are, as always, huge challenges in education, which is the bedrock of our society. The Government is fully committed to children with special educational needs to fulfil their full potential and the programme for Government makes a number of commitments to deliver this objective. Up to an additional 2,700 specialist places, made up of 400 new special classes for an average of six children each and 300 special school places, will be provided for the coming year. The NCSE has already sanctioned in excess of 209 new school classes and is engaging intensively with schools and school patron bodies to confirm additional special classes as soon as possible. On top of this, there will be well more than 1,000 places available through the normal annual movement of students progressing and graduating out of schools. There also remain special classes with vacant places in some areas of the country. Supporting the increase in provision are an additional 768 special education teachers and 1,600 special needs assistants. This means we will have more than 44,000 professionals in our education system dedicated to supporting children with special educational needs. A range of new measures to support the forward planning of special education provision was set out in Circular 0080/2024. These include new measures to address a challenge raised by the NCSE with regard to not knowing about some of the children seeking specialised placement in recent years. Parents of children with special educational needs seeking a specialised placement are now required to engage with the NCSE, so that all children who require a place for September can be supported to secure one in a timely manner. It is hugely important that we make sure those places are available in a timely manner. That is the point, and I have not heard from the Minister of State that they will be. The question was about what additional demand for special class and special school places for September 2025 is now anticipated on the back of that new process. The Minister of State did not answer that question. In fact, he spelled out what we knew already, which is what the Department is planning. How does what the Department is planning match with, or not match with, what the actual demand is? We have repeatedly heard from all quarters a real frustration as to how the Department, its agencies and the Government do so poorly at planning despite the fact that we have CSO data, AIM data, reports on children and now the new NCSE forms. Where stands the demand at this stage? How does it relate to the Department's planned roll-out of capacity? As we understand it, the plans we have in place and the placements we are working on with school patrons and schools right across the country will exceed the demand and there will be sufficient places. However, we will have to work with all families and school authorities to make sure they are in place in a timely manner. We have to be better at getting information through the AIM programme and the domiciliary care scheme. All of that information has to be available at an earlier date. One of the challenges we face is ensuring that places are made available to families and children with additional needs in a timely manner. We have to push back on that date. We have had serious engagement with the Department and the NCSE over recent weeks to make sure that is done in a timely fashion because families need to know. We are working through that in a very serious way right now and will continue to do so in the coming weeks. There is a protest at the Department of Education scheduled for tomorrow. It is a 24-hour sleep-out by parents who are demanding appropriate places for their 

In [9]:
dail_all <- rep("34th Dáil", 299) 
#since there is no Dail printed for each debate and they are the same one,
#I just extended the Dail to the length of debates.

#creating the dataframe
dataf <- data.frame(
  Dail = dail_all,
  Vol = vols,
  No = nums,
  Date = date,
  Speakers = speakers,
  Text = texts,
  Ntoken = ntokens,
  Ntypes = ntypes,
  stringsAsFactors = FALSE
)

glimpse(dataf)

Rows: 299
Columns: 8
$ Dail     <chr> "34th Dáil", "34th Dáil", "34th Dáil", "34th Dáil", "34th Dái…
$ Vol      <chr> "1063", "1063", "1063", "1063", "1063", "1063", "1063", "1063…
$ No       <chr> "6", "6", "6", "6", "6", "6", "6", "6", "6", "6", "6", "6", "…
$ Date     <chr> "2025-02-27", "2025-02-27", "2025-02-27", "2025-02-27", "2025…
$ Speakers <chr> "", "Deputy Darren O'Rourke; Minister for Education; Deputy R…
$ Text     <chr> "", "1. Deputy Darren O'Rourke asked the Minister for Educati…
$ Ntoken   <int> 0, 6404, 6404, 6404, 6404, 6404, 6404, 10143, 10143, 10143, 1…
$ Ntypes   <int> 0, 1018, 1018, 1018, 1018, 1018, 1018, 1417, 1417, 1417, 1417…

## Part Three - Responses to Statements

In [10]:
#Printing First Five Rows
head(dataf,5)

  Dail      Vol  No Date
1 34th Dáil 1063 6  2025-02-27
2 34th Dáil 1063 6  2025-02-27
3 34th Dáil 1063 6  2025-02-27
4 34th Dáil 1063 6  2025-02-27
5 34th Dáil 1063 6  2025-02-27
  Speakers
1
2 Deputy Darren O'Rourke; Minister for Education; Deputy Ruth Coppinger; Deputy Richard O'Donoghue
3 Deputy Darren O'Rourke; Minister for Education; Deputy Ruth Coppinger; Deputy Richard O'Donoghue
4 Deputy Darren O'Rourke; Minister for Education; Deputy Ruth Coppinger; Deputy Richard O'Donoghue
5 Deputy Darren O'Rourke; Minister for Education; Deputy Ruth Coppinger; Deputy Richard O'Donoghue
  Text
1

In [11]:
#Printing Last Five Rows
tail(dataf,5)

    Dail      Vol  No Date       Speakers
295 34th Dáil 1062 3  2025-01-23
296 34th Dáil 1062 3  2025-01-23
297 34th Dáil 1062 2  2025-01-22
298 34th Dáil 1062 2  2025-01-22
299 34th Dáil 1062 2  2025-01-22
    Text
295 I move: That, notwithstanding anything in Standing Orders— (1) the Whips and other nominees shall appoint thirteen members to the Select Committee standing established under Standing Order 140 (which shall be called the Select Committee on Subsidiarity (European Union Legislative Scrutiny)); (2) a Minister or Minister of State shall announce the names of the members appointed under paragraph (1) for the information of the Dáil on the first sitting day of the Dáil following their appointment; (3) Standing Order 113(2) will not apply in the case of this Committee, which shall not be subject to the d'Hondt system for the allocation of Cathaoirleach posts; (4) the Select Committee shall meet where necessary to perform the following functions: (a) to consider the potential requirement for a reasoned opinion that a draft legislative act does not comply with the principle of subsidiarity as provided for in paragraph (1) of Standing Order 142, (b) to consider such notifications under paragraphs (1)(a) and (b) of Standing Order 143 as may be referred to it by Dáil Éireann, (c) to consider potential infringements of the principle of subsidiarity as provided for in paragraph (1) of Standing Order 144, and (d) to consider other draft legislative acts which it deems appropriate, (5) the Select Committee shall have the powers defined in— (a) Standing Order 104(1), (2), (3), (4) and (10), and (b) Standing Orders 142, 143 and 144.
296 I move: That notwithstanding anything in Standing Orders and until further notice in the 34th Dáil— (a) the parties and groups shall appoint 19 members to the Committee on Standing Orders and Dáil Reform standing, established under Standing Order 128 ('the Committee'), as follows: (i) 10 members appointed by the Government parties, (ii) four members appointed by Sinn Féin, and (iii) one member each appointed by the rest of the parties and the prospective technical groups; and (b) the Ceann Comhairle shall announce the names of the members appointed under paragraph (a) for the information of the Dáil on the first sitting day of the Dáil following their appointment, and eight members of the Committee shall constitute a quorum.
297

In [12]:
#Printing the Dimensionality of the data
dim(dataf)

[1] 299   8

In [13]:
#Print total number of unique speakers in the dataset
all_speakers <- unlist(strsplit(speakers, ";")) #unlisting and sep all speakers
total_speakers <- length(unique(all_speakers))
total_speakers

[1] 94

In [15]:
#Mean Tokens after doing some light scraping.
mean(ntokens)

[1] 8029.452

In [14]:
#mean types after doing some light scraping.
mean(ntypes)

[1] 1273.572